### ISSUE TITLE
Parâmetro para informar o local do .env

### ISSUE THREAD

**Issue by pedrolauro15** [Desenroladev/pgddev#8]
Atualmente, a CLI reconhece apenas os comandos caso esteja no mesmo diretório onde se localiza o .env, deveria ser possível informar um parâmetro --enviroment ou -e para associar à um caminho personalizado de .env.

A CLI deveria também emitir um erro personalizado quando não houver .env localizado, o erro atual é o genérico (No such file or directory)

**Comment by antonielliimma** [comment]
@pedrolauro15 muito obrigado pela sugestão, funcionalidade implementada na versão 2.0.5

`npm i -g @desenroladev/cli`

Vlw cara tudo de bom!
